In [2]:
import pandas as pd

from mlxtend.frequent_patterns import (
    apriori,
    association_rules
)

In [3]:
master = pd.read_csv(
    "../data/cleaned/master_dataset.csv"
)

In [4]:
basket = (
    master
    .groupby(
        ["order_id",
         "product_category_name_english"]
    )["product_id"]
    .count()
    .unstack()
    .fillna(0)
)

In [11]:
basket = basket > 0

In [12]:
basket.head()

product_category_name_english,agro_industry_and_commerce,air_conditioning,art,arts_and_craftmanship,audio,auto,baby,bed_bath_table,books_general_interest,books_imported,...,security_and_services,signaling_and_security,small_appliances,small_appliances_home_oven_and_coffee,sports_leisure,stationery,tablets_printing_image,telephony,toys,watches_gifts
order_id,,,,,,,,,,,,,,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
00018f77f2f0320c557190d7a144bdd3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
000229ec398224ef6ca0657da4fc703e,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
00024acbcdf0a6daa1e931b038114c75,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
00042b26cf59d7ce69dfabb4e55b4fd9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
frequent_items = apriori(
    basket,
    min_support=0.01,
    use_colnames=True
)

In [8]:
frequent_items.head()

    support                            itemsets
0  0.040070                   frozenset({auto})
1  0.029664                   frozenset({baby})
2  0.096827         frozenset({bed_bath_table})
3  0.068777  frozenset({computers_accessories})
4  0.010920         frozenset({consoles_games})

In [14]:
basket.dtypes.head()

product_category_name_english
agro_industry_and_commerce    bool
air_conditioning              bool
art                           bool
arts_and_craftmanship         bool
audio                         bool
dtype: object

In [16]:
rules = association_rules(
    frequent_items,
    metric="lift",
    min_threshold=1
)

In [17]:
rules.head()

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

In [18]:
rules.sort_values(
    "lift",
    ascending=False
).head(10)

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

In [19]:
rules.shape

(0, 14)

In [20]:
rules.sort_values("lift", ascending=False).head(10)

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

In [21]:
master.groupby("order_id")["product_category_name_english"] \
      .nunique() \
      .value_counts()

product_category_name_english
1    96530
0     2185
2      711
3       15
Name: count, dtype: int64

In [22]:
frequent_items["length"] = (
    frequent_items["itemsets"]
    .apply(len)
)

frequent_items["length"].value_counts()

length
1    21
Name: count, dtype: int64

In [23]:
frequent_items = apriori(
    basket,
    min_support=0.001,
    use_colnames=True
)

In [24]:
frequent_items["length"] = (
    frequent_items["itemsets"]
    .apply(len)
)

frequent_items["length"].value_counts()

length
1    51
Name: count, dtype: int64

In [25]:
rules = association_rules(
    frequent_items,
    metric="lift",
    min_threshold=1
)

Market Basket Analysis was attempted using the Apriori algorithm. However, approximately 98% of orders contained products from only one category, preventing the formation of frequent multi-item itemsets. Therefore, association rules could not be generated, indicating that category-level basket analysis is not suitable for this dataset.